"""ajuste usuario admin

Revision ID: 1db96f52bea9
Revises: fc89630fb585
Create Date: 2026-07-26 17:29:18.940769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1db96f52bea9'
down_revision: Union[str, Sequence[str], None] = 'fc89630fb585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agendamentos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agendamentos', 'servico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agendamentos', 'data',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('agendamentos', 'horario',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.add_column('empresas', sa.Column('cnpj', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'empresas', ['cnpj'])
    op.add_column('usuarios', sa.Column('tipo', sa.String(length=20), nullable=True))
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('usuarios', 'tipo')
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_column('empresas', 'cnpj')
    op.alter_column('agendamentos', 'horario',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('agendamentos', 'data',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('agendamentos', 'servico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agendamentos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agendamentos', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
